# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Concat.py
# Created on: 2021-05-20 13:56:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("//cormplbrbs1.corp.pbwan.net/Shared/LandAspects/GSS/Admin/Manchester/Technical/13 Delivery Tools/HS2_Tools_20190213.tbx")


# Local variables:
LOP_Pnumbers = "LOP_Pnumbers"
Monitoring_Unique_Ref_Concatenated = LOP_Pnumbers

# Process: Concatenate Monitoring Unique Ref
arcpy.gp.toolbox = "//cormplbrbs1.corp.pbwan.net/Shared/LandAspects/GSS/Admin/Manchester/Technical/13 Delivery Tools/HS2_Tools_20190213.tbx";
# Warning: the toolbox //cormplbrbs1.corp.pbwan.net/Shared/LandAspects/GSS/Admin/Manchester/Technical/13 Delivery Tools/HS2_Tools_20190213.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.MergeRowValues22(...) with arcpy.MergeRowValues22_ALIAS(...)
arcpy.gp.MergeRowValues22(LOP_Pnumbers, "PNumber", "OwnershipReferenceNumber", "Ownership_Reference", ",")

