# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Dissolve_Stats.py
# Created on: 2020-10-16 12:43:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
PRP_MCL_C863_LandAcquisitionAreas_Ply = "PRP_MCL_C863_LandAcquisitionAreas_Ply"
PRP_MCL_C863_LandAcquisition = "C:\\Users\\UKPXR011\\Documents\\ArcGIS\\Default.gdb\\PRP_MCL_C863_LandAcquisition"

# Process: Dissolve
arcpy.Dissolve_management(PRP_MCL_C863_LandAcquisitionAreas_Ply, PRP_MCL_C863_LandAcquisition, "LAAID", "LAAID COUNT", "MULTI_PART", "DISSOLVE_LINES")

