# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Fuck Arc.py
# Created on: 2019-11-05 12:05:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Page_Test_Intersect1 = "Page_Test_Intersect1"
Page_Test_Intersect1_Dissolv1 = "C:\\Users\\UKPXR011\\Documents\\ArcGIS\\Default.gdb\\Page_Test_Intersect1_Dissolv1"

# Process: Dissolve
arcpy.Dissolve_management(Page_Test_Intersect1, Page_Test_Intersect1_Dissolv1, "UniqueID", "Number MIN", "MULTI_PART", "DISSOLVE_LINES")

