# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Select.py
# Created on: 2020-02-20 11:13:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Land_Ownership_Parcels = "Land Ownership Parcels"
LandOwnershipParcels_Select = "C:\\Users\\UKPXR011\\Documents\\ArcGIS\\Default.gdb\\LandOwnershipParcels_Select"

# Process: Select
arcpy.Select_analysis(Land_Ownership_Parcels, LandOwnershipParcels_Select, "Include = 'Yes'")

