# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Street_View_URL.py
# Created on: 2019-08-30 13:51:12.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Street_View_URL <Roads> <Ownership> <Create_Folder_for_data>
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Roads = arcpy.GetParameterAsText(0)
if Roads == '#' or not Roads:
    Roads = "Roads" # provide a default value if unspecified

Ownership = arcpy.GetParameterAsText(1)
if Ownership == '#' or not Ownership:
    Ownership = "Ownership" # provide a default value if unspecified

Create_Folder_for_data = arcpy.GetParameterAsText(2)
if Create_Folder_for_data == '#' or not Create_Folder_for_data:
    Create_Folder_for_data = "C:\\Users\\UKPXR011\\Desktop" # provide a default value if unspecified

# Local variables:
RoadsL3L4_GeneratePointsAlon1 = "%Scratch%\\RoadsL3L4_GeneratePointsAlon1"
RoadsL3L4_GeneratePointsAlon2 = "%Scratch%\\RoadsL3L4_GeneratePointsAlon2"
RoadsL3L4_GeneratePointsAlon2__2_ = RoadsL3L4_GeneratePointsAlon2
LandOwnership__7_ = RoadsL3L4_GeneratePointsAlon2__2_
LandOwnership_SpatialJoin = "%Scratch%\\LandOwnership_SpatialJoin"


# Process: Add Field
arcpy.AddField_management(Ownership, "lat", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(Ownership, "Lng", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(Ownership, "StreetViewURL", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Create Folder
arcpy.CreateFolder_management(Create_Folder_for_data, "Street_View")

# Process: Create File GDB
arcpy.CreateFileGDB_management(Create_Folder_for_data, "Scratch", "CURRENT")

# Process: Generate Points Along Lines
arcpy.GeneratePointsAlongLines_management(Roads, RoadsL3L4_GeneratePointsAlon1, "DISTANCE", "10 Meters", "", "END_POINTS")

# Process: Project
arcpy.Project_management(RoadsL3L4_GeneratePointsAlon1, RoadsL3L4_GeneratePointsAlon2, "PROJCS['WGS_1984_Web_Mercator_Auxiliary_Sphere',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator_Auxiliary_Sphere'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],PARAMETER['Auxiliary_Sphere_Type',0.0],UNIT['Meter',1.0]]", "'OSGB_1936_To_ETRS_1989_1 + ETRS_1989_To_WGS_1984'", "PROJCS['British_National_Grid',GEOGCS['GCS_OSGB_1936',DATUM['D_OSGB_1936',SPHEROID['Airy_1830',6377563.396,299.3249646]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',400000.0],PARAMETER['False_Northing',-100000.0],PARAMETER['Central_Meridian',-2.0],PARAMETER['Scale_Factor',0.9996012717],PARAMETER['Latitude_Of_Origin',49.0],UNIT['Meter',1.0]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: Add Field (4)
arcpy.AddField_management(RoadsL3L4_GeneratePointsAlon2, "lat", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (5)
arcpy.AddField_management(RoadsL3L4_GeneratePointsAlon2__2_, "Lng", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Spatial Join
arcpy.SpatialJoin_analysis(Ownership, LandOwnership__7_, LandOwnership_SpatialJoin, "JOIN_ONE_TO_ONE", "KEEP_ALL", "OwnershipReferenceNumber \"Ownership Reference Number\" true true false 4 Long 0 0 ,First,#,Ownership,OwnershipReferenceNumber,-1,-1;GlobalID \"GlobalID\" false false true 38 GlobalID 0 0 ,First,#,Ownership,GlobalID,-1,-1;SHAPE_Length \"SHAPE_Length\" false true true 8 Double 0 0 ,First,#,Ownership,SHAPE_Length,-1,-1;SHAPE_Area \"SHAPE_Area\" false true true 8 Double 0 0 ,First,#,Ownership,SHAPE_Area,-1,-1;lat \"lat\" true true false 8 Double 0 0 ,First,#,Ownership,lat,-1,-1;Lng \"Lng\" true true false 8 Double 0 0 ,First,#,Ownership,Lng,-1,-1;StreetViewURL \"StreetViewURL\" true true false 100 Text 0 0 ,First,#,Ownership,StreetViewURL,-1,-1;lat \"lat\" true true false 0 Double 0 0 ,First,#,%Scratch%\\RoadsL3L4_GeneratePointsAlon2,lat,-1,-1;Lng \"Lng\" true true false 0 Double 0 0 ,First,#,%Scratch%\\RoadsL3L4_GeneratePointsAlon2,Lng,-1,-1", "INTERSECT", "", "")

# Process: Add Join
arcpy.AddJoin_management(Ownership, "OwnershipReferenceNumber", LandOwnership_SpatialJoin, "OwnershipReferenceNumber", "KEEP_ALL")

# Process: Calculate Field
arcpy.CalculateField_management(Ownership, "lat", "[LandOwnership_SpatialJoin.lat]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Ownership, "Lng", "[LandOwnership_SpatialJoin.Lng]", "VB", "")

# Process: Remove Join
arcpy.RemoveJoin_management(Ownership, "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Ownership, "StreetViewURL", "'http://maps.google.com/maps?q=&layer=c&cbll='+str(!lat!)+','+ str(!Lng!)+'&cbp=11,0,0,0,0'", "PYTHON", "")

