# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Sunil_Extents.py
# Created on: 2021-10-26 15:04:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/UKPXR011/Desktop/Scripts/Noitce Plans/WSP Toolbox.pyt")


# Local variables:

# Process: Extent Calculator
arcpy.ExtentCalculator_WSP Toolbox("", "A3")

