# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SyncChangesReplica1way_AllSchemes.py
# Created on: 2017-10-11 13:19:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

print ("Sync started")

# Local variables:
WSP_HS2_Phase_2A_DEFAULT_GSSWebServiceUser_sde = "C:\Users\UKPXR011\AppData\Roaming\ESRI\Desktop10.5\ArcCatalog\HS2-Phase2A-Manchester-GSS.sde"
WSP_HS2_Phase_2A_DEFAULT_GSSWebServiceUser_sde__2_ = WSP_HS2_Phase_2A_DEFAULT_GSSWebServiceUser_sde
HS2p2A_1wayReplicaForWebPublishing_gdb__2_ = WSP_HS2_Phase_2A_DEFAULT_GSSWebServiceUser_sde
HS2p2A_1wayReplicaForWebPublishing_gdb = "\\10.44.252.11\GSS_Data\62240842-HS2_Phase_2A\13_GSS\132_GIS\GIS_Data\Geodatabases\Replication_for_Web_Publishing\HS2p2A_1wayReplicaForWebPublishing_2021.gdb"

arcpy.SynchronizeChanges_management(WSP_HS2_Phase_2A_DEFAULT_GSSWebServiceUser_sde, "HS2p2A_1wayReplicaForWebPublishing_20200526", HS2p2A_1wayReplicaForWebPublishing_gdb, "FROM_GEODATABASE1_TO_2", "IN_FAVOR_OF_GDB1", "BY_OBJECT", "DO_NOT_RECONCILE")
print ("HS2 Phase 2A sync complete ....")



