# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SyncChangesReplica1way_AllSchemes.py
# Created on: 2017-10-11 13:19:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

print ("Sync started")

# Local variables:
WSP_Heathrow_DEFAULT_GSSWebServiceUser_sde = "Database Connections\\WSP Heathrow DEFAULT GSSWebServiceUser.sde"
WSP_Heathrow_DEFAULT_GSSWebServiceUser_sde__2_ = WSP_Heathrow_DEFAULT_GSSWebServiceUser_sde
HAS_3_1wayReplicaForWebPublishing_gdb__2_ = WSP_Heathrow_DEFAULT_GSSWebServiceUser_sde
HAS_3_1wayReplicaForWebPublishing_gdb = "\\\\10.44.252.11\\GSS_Data\\Heathrow-Papplewick\\13_GSS\\132_GIS\\GIS_Data\\Geodatabases\\Replication_for_Web_Publishing\\HAS_3_1wayReplicaForWebPublishing.gdb"

# Process: Synchronize Changes
arcpy.SynchronizeChanges_management(WSP_Heathrow_DEFAULT_GSSWebServiceUser_sde, "GSSWEBSERVICEUSER.ReplicaForPublishing1way_20181121", HAS_3_1wayReplicaForWebPublishing_gdb, "FROM_GEODATABASE1_TO_2", "IN_FAVOR_OF_GDB1", "BY_OBJECT", "DO_NOT_RECONCILE")
print ("Heathrow sync complete ....")

print ("Sync complete")
